//! Stamp the build's provenance into the binary (FEAT-088).
//!
//! `--version` alone answers "which release is this?" and not "which build?". Those differ whenever
//! a release is rebuilt under the same tag — an interim fix, a corrected packaging step — which is
//! exactly the case `self-update` exists to notice. The commit hash is the human-readable half of
//! that answer; the binary's checksum is the machine-readable one.
//!
//! Everything here degrades to `unknown` rather than failing the build: a crates.io tarball has no
//! `.git`, and a build that breaks because git is missing is worse than a version string that says
//! so plainly.

use std::process::Command;

fn main() {
    // Re-run when HEAD moves. `.git/HEAD` covers a checkout; the packed ref covers a commit on the
    // current branch. Neither existing is fine — the fallbacks below handle it.
    for path in [".git/HEAD", ".git/refs/heads"] {
        let p = std::path::Path::new("../../..").join(path);
        if p.exists() {
            println!("cargo:rerun-if-changed={}", p.display());
        }
    }
    println!("cargo:rerun-if-env-changed=KANBANR_GIT_SHA");
    println!("cargo:rerun-if-env-changed=KANBANR_BUILD_DATE");

    // CI can pass it in (a shallow clone or an exported tree may have no usable git metadata).
    let sha = std::env::var("KANBANR_GIT_SHA")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .or_else(|| git(&["rev-parse", "--short=12", "HEAD"]))
        .unwrap_or_else(|| "unknown".to_string());

    // A build from a modified tree is not the commit it names, and saying so is the whole point.
    let dirty = git(&["status", "--porcelain"]).is_some_and(|s| !s.trim().is_empty());
    let sha = if dirty && sha != "unknown" {
        format!("{sha}-dirty")
    } else {
        sha
    };

    // Passed in too, for a build with no `.git` at all — the container image's (FEAT-144).
    let date = std::env::var("KANBANR_BUILD_DATE")
        .ok()
        .filter(|s| !s.trim().is_empty())
        .or_else(|| git(&["log", "-1", "--format=%cd", "--date=short"]))
        .unwrap_or_else(|| "unknown".to_string());

    println!("cargo:rustc-env=KANBANR_GIT_SHA={sha}");
    println!("cargo:rustc-env=KANBANR_BUILD_DATE={date}");

    embed_skill();
}

/// Embed the Claude Code skill this binary drives (FEAT-141): `skill/kanbanr/` — SKILL.md, the
/// hook scripts and their prompt — so `kanbanr skill install` writes the skill of *this* release,
/// never a newer or older one from a branch. Absent (a crate built outside the repository), the
/// table is empty and `skill install` says so.
fn embed_skill() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../skill/kanbanr");
    println!("cargo:rerun-if-changed={}", root.display());
    let mut files = Vec::new();
    collect(&root, &root, &mut files);
    files.sort();
    let mut out = String::from(
        "// @generated by build.rs — the skill this binary carries (FEAT-141).\n\
         pub static SKILL_FILES: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({rel:?}, include_bytes!({:?})),\n",
            abs.display().to_string()
        ));
    }
    out.push_str("];\n");
    let dest = std::path::Path::new(&std::env::var("OUT_DIR").unwrap()).join("skill_files.rs");
    std::fs::write(dest, out).unwrap();
}

fn collect(
    root: &std::path::Path,
    dir: &std::path::Path,
    out: &mut Vec<(String, std::path::PathBuf)>,
) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') || name == "__pycache__" {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            let rel = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            out.push((rel, path.canonicalize().unwrap_or(path)));
        }
    }
}

fn git(args: &[&str]) -> Option<String> {
    let out = Command::new("git")
        .args(args)
        .current_dir("../../..")
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8(out.stdout).ok()?.trim().to_string();
    (!s.is_empty()).then_some(s)
}
