//! Bake the built monitor into the binary (FEAT-084 R-1).
//!
//! The stated constraint is one binary installable without a toolchain, and it was only ever true
//! of the CLI: `kanbanr serve` served whatever `--ui-dir` pointed at, so the monitor needed Node and
//! a build, and the release tarball shipped the executable alone — a download gave an API with no
//! web view and nothing saying why.
//!
//! The assets are stored **gzipped** and decompressed once at startup, so the binary grows by their
//! compressed size (~0.9 MB of 3.4 MB raw) rather than their raw size (R-5). Over localhost there is
//! nothing to gain from serving the compressed bytes on the wire, and decompressing at startup keeps
//! the serving path free of content-negotiation.
//!
//! When `web/dist` is absent the table is empty and the build still succeeds. That is deliberate:
//! a contributor running `cargo build` has no reason to have Node, and a build that fails on a
//! missing generated directory teaches people to avoid the build. The daemon reports the absence at
//! startup instead (R-3) — an unreported absence is this project's recurring failure.

use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let dist = std::env::var("KANBANR_UI_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            // api/crates/kanbanr-server -> repo root -> web/dist
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../web/dist")
        });
    println!("cargo:rerun-if-env-changed=KANBANR_UI_DIST");
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut entries = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
        entries.sort_by(|a: &(String, PathBuf), b| a.0.cmp(&b.0));
    }

    // One blob per file, gzipped into OUT_DIR and referenced by include_bytes!.
    let mut src = String::from(
        "// @generated by build.rs — the monitor's assets, gzipped.\n\
         pub static ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (i, (rel, path)) in entries.iter().enumerate() {
        let raw = std::fs::read(path).unwrap_or_default();
        let name = format!("asset_{i}.gz");
        let mut enc = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::best());
        enc.write_all(&raw).expect("gzip");
        std::fs::write(out.join(&name), enc.finish().expect("gzip finish")).expect("write asset");
        src.push_str(&format!(
            "    ({rel:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{name}\"))),\n"
        ));
    }
    src.push_str("];\n");
    std::fs::write(out.join("ui_assets.rs"), src).expect("write ui_assets.rs");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            // Published paths are URL paths: always forward slashes, whatever built them.
            out.push((rel.to_string_lossy().replace('\\', "/"), path.clone()));
        }
    }
}
